# Generated by Django 4.2.3 on 2025-03-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_dashboardstats_product_remove_inventory_medicine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='batch_number',
            new_name='batchNumber',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='expiry_date',
            new_name='expiryDate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='reorder_level',
            new_name='reorderLevel',
        ),
    ]
